# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy pylint
    - name: Lint with pylint
      run: |
        pylint logria
      continue-on-error: true
    - name: Static Analysis with mypy
      run: |
        mypy . --ignore-missing-imports
      continue-on-error: true
    - name: Test with stdlib unittest
      run: |
        echo 'Setting up directory structure'
        mkdir .logria
        mkdir .logria/patterns
        mkdir .logria/sessions
        ls -a
        ls .logria
        echo 'Creating sample files'
        touch '.DS_Store'
        touch 'File - readme'
        touch 'File - Sample Access Log'
        touch 'Cmd - Generate Test Logs'
        python -m unittest discover -v
